; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [platformio]

[env:esp32-c6-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino

; Defaults
; platform = espressif32
; board = esp32-c6-devkitm-1
; framework = arduino

upload_speed = 921600
monitor_speed = 115200

; Optional Fixed Com Port. This is useful if you have other COM devices and Auto does not work.
; upload_port = COM61
; monitor_port = COM61

; A couple of library folders are placed/included in libdeps but not in the below as the libraries are not in pio lib.
lib_deps =
  gyverlibs/GyverOLED@^1.6.1
  adafruit/Adafruit NeoPixel @ ^1.15.2
  sparkfun/SparkFun TMP102 Breakout @ ^1.1.2 
  jgromes/RadioLib @ ^7.4.0
  robtillaart/I2C_EEPROM @ ^1.9.4
  adafruit/Adafruit Unified Sensor @ ^1.1.15

